### ISSUE TITLE
Cannot Load Data-image

### ISSUE THREAD

**Issue by petersiow-stu** [gyrocode/jplayer-jukebox#1]
I add the album art's path to data-image but it cannot be displayed.  Then I found that the demo page cannot show the image too.

**Comment by mpryvkin** [comment]
It works correctly in the demo, see [project page](http://www.gyrocode.com/projects/jplayer-jukebox/) and ".MP3 file" link. Screenshot is shown below:

<img src="http://i.imgur.com/EX3MRF5.png">

 It uses the following code: 

```
<a class="jp-page-link" href="media/mp3.mp3" title="" data-artist="Lucas Gonze" data-image="media/cover1.jpg" data-download="1" data-buy="https://www.freesound.org/people/lucasgonze/sounds/58970/">.MP3 file</a>
```

where `media/cover1.jpg` is a path to image file. It is relative to the page itself. 

Make sure you're using correct path. 

If it is still doesn't work, see if you can create a reproducible example on https://jsfiddle.net.
