### ISSUE TITLE
Browser Keyboard Shortcuts Not Working?

### ISSUE THREAD

**Issue by cmart720** [gyrocode/jplayer-jukebox#2]
Hi -- this is an awesome replacement player! Thanks for your efforts. 

We just noticed something when testing it out. For some reason, browser keyboard shortcuts such as Command-F and Command-S do not work when you load a page containing the player. Sometimes, opening or closing the player (if it's floating) will allow these keyboard shortcuts to temporarily resume functionality. If the player is pinned to the bottom, it seems the functionality never works.

We are testing on Mac computers (10.11) using Chrome and Safari.

**Comment by mpryvkin** [comment]
I think this is because jPlayer automatically enables key handling, see http://jplayer.org/latest/developer-guide/#jPlayer-function-keys

Try setting `keyEnabled` option to  `false` as shown below.

```
var jpjb = new jPlayerJukebox({
     keyEnabled: false
});
```

In the meantime I can disable key handling by default, it seems useless.

**Comment by mpryvkin** [comment]
I have updated the project page (https://www.gyrocode.com/projects/jplayer-jukebox), see if it works for you.

**Comment by cmart720** [comment]
Works like a charm! Thanks so much for quick reply and adjustment!

Best,
Chris
