### ISSUE TITLE
Way to open "closed" player when audio play button is clicked on page?

### ISSUE THREAD

**Issue by cmart720** [gyrocode/jplayer-jukebox#3]
Hi again -- This is more of a question than an issue. In the original Yahoo Media Player, the player would start out "closed" by default (so there was only an arrow in the bottom left corner of the page.) If you clicked on the play button for an audio file in a page, the player would automatically "open" and start playing. The jplayer-jukebox seems to stay closed if it is closed and you click a play button for an audio file. Is there any way to replicate the functionality of the original YMP so that the player automatically opens? Or if it's possible for this to be an option?

The main concern is that a user may not recognize the player is there / available if it is closed and consequently not see all the great jplayer playback options.

Love the player -- know very little about programming though! Thanks!
Chris

**Comment by mpryvkin** [comment]
Chris, see [this example](https://jsfiddle.net/txxde6eh/) for demonstration on how to do it. 

Please leave questions or comments on [this page](http://www.gyrocode.com/articles/jplayer-jukebox-add-on-yahoo-media-player-replacement/#respond) instead.
