### ISSUE TITLE
Hidden mode on small screens

### ISSUE THREAD

**Issue by Bilbo1960** [gyrocode/jplayer-jukebox#4]
I have the player in "hidden" mode:

```
<script type="text/javascript">   
   $(document).ready(function(){
      // Initialize jPlayerJukebox
      var jpjb = new jPlayerJukebox({
         'jukeboxOptions': {
        'viewState': 'hidden',
        'autoAdvance': '',
         }
      });
   });
</script>
```

Hidden mode works on wide screens, however, in Chome, FF and Android mobile (haven't checked further) the player appears in small screens at the bottom of the screen. How can I make player invisible in all devices?
Thanks in advance.

**Comment by mpryvkin** [comment]
Thanks for reporting this issue, I have added a fix to resolve it.
